version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: labruja12
      MYSQL_USER: root
      MYSQL_PASSWORD: labruja12
    ports:
      - 3307:3306
    volumes:
      - mysqldata:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_labrujastore?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: labruja12
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - 9080:8080
    depends_on:
      - db

volumes:
  mysqldata:
