services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: labruja12
      MYSQL_USER: root
      MYSQL_PASSWORD: labruja12
    ports:
      - 3307:3306
    volumes:
      - mysqldata:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_HOST: mysqldb 
      MYSQL_USER: root
      MYSQL_PASSWORD: labruja12
      MYSQL_PORT: 3306
    ports:
      - 9080:8080
volumes:
  mysqldata: 